### ISSUE TITLE
Configure fieldRename for enums in build.yaml

### ISSUE THREAD

**Issue by ookami-kb** [google/json_serializable.dart#1021]
We have now [support](https://github.com/google/json_serializable.dart/issues/929) for `fieldRename` on a per-enum basis (rather than per-value), which simplifies the setup.

In our case, all enums coming from the backend are serialized in PascalCase, so it would be great to have an option to configure it in `build.yaml`, the same as we can do for other fields with `field_rename`.

**Comment by Aqluse** [comment]
I need it too

**Comment by JPM84** [comment]
Seems to work or am I missing something? Just add the following to build.yaml -->
```
targets:
  $default:
    builders:
      json_serializable:
        options:
          field_rename: snake
```

**Comment by kevmoo** [comment]
@JPM84 – nope. This does fields within a class. The request here is for enum values.

**Comment by lohnn** [comment]
I'm looking into this and I'm taking a stab at it. I I've got it more or less working now but I do have a big question mark to solve left.
Currently I've implemented it so the `JsonEnum` config is read from the same place as `JsonSerializable`, but that would mean that field_rename would always be shared between the two.

For example this:
```yaml
targets:
  $default:
    builders:
      json_serializable:
        options:
          field_rename: kebab
```
would result in kebab-case as fallback for all Enums and classes annotated with JsonSerializable.

Any ideas or recommendations on how we should solve this properly?
