### ISSUE TITLE
`field_rename: snake` causes cast problem in `fromJson` for some json responses

### ISSUE THREAD

**Issue by yh-luo** [google/json_serializable.dart#1107]
### Description
Setting `field_rename: snake` causes cast errors in some json responses (but not all). But when the option is removed, the problem is no longer present. I found the problem during testing. Because the text contains special characters `\r\n`, could it cause the problem?

### Error message
```
00:00 +5: test/app_uat_test.dart: fetchServices works properly
CheckedFromJsonException
Could not create `ServiceData`.
There is a problem with "service_name".
type 'Null' is not a subtype of type 'String' in type cast #0      $checkedConvert (package:json_annotation/src/checked_helpers.dart:94:5)
#1      $checkedCreate._checkedConvert (package:json_annotation/src/checked_helpers.dart:31:7)
#2      _$ServiceDataFromJson.<anonymous closure> (package:app_api/src/models/content.g.dart:17:39)
#3      $checkedCreate.<anonymous closure> (package:json_annotation/src/checked_helpers.dart:36:22)
#4      $checkedNew (package:json_annotation/src/checked_helpers.dart:54:23)
#5      $checkedCreate (package:json_annotation/src/checked_helpers.dart:33:10)
#6      _$ServiceDataFromJson (package:app_api/src/models/content.g.dart:11:65)
#7      new ServiceData.fromJson (package:app_api/src/models/content.dart:20:7)
#8      AppUatClient.fetchServices (package:app_api/src/app_uat.dart:607:30)
<asynchronous suspension>
#9      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:125:47)
<asynchronous suspension>
```

### Minimal reproducible example
```dart
List<ServiceData> _dataChunks = <ServiceData>[];
final serverResp = jsonEncode({
  "status": "Y",
  "services": [
    {
      "seq": 1,
      "serviceName": '免費購物專車',
      "serviceIntroduction":
          "1F 蘭雅側出口處乘車專用站牌\r\n天母線、芝山捷運線2條路線\r\n發車時間及行駛路線\r\n請參考服務專區 > 交通資訊",
      "serviceImageUrl":
          "https://img.png"
    }
  ]
});

final response = jsonDecode(serverResp);
for (var serviceJson in response['services']) {
  _dataChunks.add(ServiceData.fromJson(serviceJson));
}
```
### Data model class
```dart
@JsonSerializable()
class ServiceData {
  const ServiceData({
    required this.seq,
    required this.serviceName,
    required this.serviceIntroduction,
    required this.serviceImageUrl,
  });

  final int seq;
  final String serviceName;
  final String serviceIntroduction;
  final String serviceImageUrl;

  factory ServiceData.fromJson(Map<String, dynamic> json) =>
      _$ServiceDataFromJson(json);
}
```

### build.yaml

- Causes errors
```yaml
targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - implicit_dynamic_parameter
      json_serializable:
        options:
          field_rename: snake
          create_to_json: false
          checked: true
          explicit_to_json: true
```

- Works as expected (`field_rename: snake` is removed)
```yaml
targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - implicit_dynamic_parameter
      json_serializable:
        options:
          create_to_json: false
          checked: true
          explicit_to_json: true
```

### Flutter & Dart version
```
Flutter 2.10.2 • channel stable •
https://github.com/flutter/flutter.git
Framework • revision 097d3313d8 (2 weeks ago) • 2022-02-18
19:33:08 -0600
Engine • revision a83ed0e5e3
Tools • Dart 2.16.1 • DevTools 2.9.2

Dart SDK version: 2.16.1 (stable) (Tue Feb 8 12:02:33 2022 +0100) on "macos_x64"
```

### pubspec.yaml
```yaml
name: app_api
description: API helper
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  json_annotation: ^4.4.0
  http: ^0.13.4
  intl: ^0.17.0
  mockito: ^5.0.17
dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  json_serializable: ^6.1.4
  test: ^1.17.12
```
