### ISSUE TITLE
The function $enumDecode isn't defined

### ISSUE THREAD

**Issue by osharaki** [google/json_serializable.dart#1140]
One of the properties in my class is an enum, and when I generate the JSON serialization code for it, I end up with a function [`$enumDecode`](https://pub.dev/documentation/json_annotation/latest/json_annotation/$enumDecode.html) in the _.g.dart_ file. However, the function isn't recognized.
> The function `$enumDecode` isn't defined.

I have the dependencies as they are listed [here](https://github.com/google/json_serializable.dart/tree/58f46ade0d2da55ec7274760c58d90e0b91f107a/example).

Interestingly, downgrading to
```yaml
dependencies:
  json_annotation: 4.0.1

dev_dependencies:
  json_serializable: 4.1.4
  build_runner: 2.1.0
```
generates a private `_$enumDecode` instead, which is defined locally.

`flutter --version` output:
> Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (6 months ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4

**Comment by pawlowskim** [comment]
Hey. 
`$enumDecode` was added in 6.0.0, previously i was `_$enumDecode`: https://pub.dev/packages/json_serializable/changelog#600

**Comment by osharaki** [comment]
> Hey. `$enumDecode` was added in 6.0.0, previously i was `_$enumDecode`: https://pub.dev/packages/json_serializable/changelog#600

Thanks for the info. Any insight then as to why this set of dependencies would end up generating a method that isn't defined?
```yaml
dependencies:
  json_annotation: ^4.4.0

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
```
From what I can tell, `$enumDecode` should exist in both `json_annotation` and `json_serializable` in the provided versions.

**Comment by kevmoo** [comment]
@osharaki – there is no reason to include it in `json_serializable` because that code is never imported into your running code. It's just the builder.

**Comment by osharaki** [comment]
Yeah, I meant `json_annotation` only. Sorry for the confusion.
Still, it's not clear to me why the function undefined error would occur with these versions.

**Comment by osharaki** [comment]
No prefix. Interesting that that could make a difference though.
However, I don't wanna unnecessarily drag out this thread any longer. I wouldn't completely rule out some mistake on my part that I didn't document here. I'm not blocked by this anymore and many modules in our project are now using `$enumDecode` without issues.

My questions at this point are purely out of curiosity, so please feel free to mark this one closed.

**Comment by kevmoo** [comment]
Could you paste in code from your regular library – the whole thing. Or a
minimal repo. Does your library import 'json_annotation'?

**Comment by osharaki** [comment]
Yes, the library imports `json_annotation`: `import 'package:json_annotation/json_annotation.dart';`

I just ran the builder again with the same versions as before (the ones mentioned [here](https://github.com/google/json_serializable.dart/tree/58f46ade0d2da55ec7274760c58d90e0b91f107a/example)) and `$enumDecode` is recognized. 

Here's the `pubspec.yaml`:
```yaml
...
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 1.0.4
  json_serializable: ^6.0.0
  build_runner: ^2.0.0
```

One difference is that the Flutter version being used now is `2.10.5` as opposed to `2.5.3` when I initially posted this.
