### ISSUE TITLE
New Enums throws a [SEVERE] error

### ISSUE THREAD

**Issue by cgutierr-zgz** [google/json_serializable.dart#1148]
Hi,

New flutter version `3.0.0` with dart version `2.17.0` has introduced **enhanced enums**.
I use one of this enums for some class which gets converted into json/ from json.

Here you can have a sample:
```dart
enum MyExample {
  example0('example0', ExampleWidget0()),
  example1('example1', ExampleWidget1()),
  example2('example2', ExampleWidget2()),
  example3('example3', ExampleWidget3()),
  example4('example4', ExampleWidget4());

  const MyExample(this.value1, this.value2);

  final String value1;
  final Widget value2;

  @override
  String toString() => '$name: [$value1][$value2]';
}
```

Now when I run the build runner I get this error:
```sh
[SEVERE] json_serializable:json_serializable on lib/my_example_file.dart:

This builder requires Dart inputs without syntax errors.
However, package:example/my_example_file.dart (or an existing part) contains the following errors.
my_example_file.dart:2:11: Expected to find '}'.

Try fixing the errors and re-running the build.
```
---

`flutter --version`
<details >
<summary>Output</summary>

>Flutter 3.0.0 • channel stable • https://github.com/flutter/flutter.git
>Framework • revision ee4e09cce0 (2 days ago) • 2022-05-09 16:45:18 -0700
>Engine • revision d1b9a6938a
>Tools • Dart 2.17.0 • DevTools 2.12.2

</details>

**Comment by vicdotdevelop** [comment]
+1

**Comment by kevmoo** [comment]
Will look now!

**Comment by kevmoo** [comment]
Oh! Quick idea: change your SDK constraint to `dart: ">=2.17.0 <3.0.0"`

**Comment by cgutierr-zgz** [comment]
> Oh! Quick idea: change your SDK constraint to `dart: ">=2.17.0 <3.0.0"`

I have that version yep, new Enums don't won't without 2.17

**Comment by kevmoo** [comment]
Is this set in your pubspec?

```yaml
environment:
  sdk: '>=2.17.0 <3.0.0'
```

?

**Comment by cgutierr-zgz** [comment]
> Is this set in your pubspec?
> 
> ```yaml
> environment:
>   sdk: '>=2.17.0 <3.0.0'
> ```
> 
> ?

Yep

> 
![Screenshot 2022-05-12 at 23 13 32](https://user-images.githubusercontent.com/18635739/168169164-76f33c3f-3195-45a4-a3fe-21fc12019b66.png)

**Comment by kevmoo** [comment]
Just tried this out. 

```dart
import 'package:flutter/material.dart';
import 'package:json_annotation/json_annotation.dart';

part 'sample.g.dart';

@JsonSerializable()
class Sample {
  final MyExample value;

  Sample(this.value);

  factory Sample.fromJson(Map<String, dynamic> json) => _$SampleFromJson(json);

  Map<String, dynamic> toJson() => _$SampleToJson(this);
}

enum MyExample {
  example0('example0', BackButton());

  const MyExample(this.value1, this.value2);

  final String value1;
  final Widget value2;

  @override
  String toString() => '$name: [$value1][$value2]';
}
```

Works fine for me!

Have you ran `flutter pub get` recently? Try that.

**Comment by cgutierr-zgz** [comment]
> Just tried this out.
> 
> ```dart
> import 'package:flutter/material.dart';
> import 'package:json_annotation/json_annotation.dart';
> 
> part 'sample.g.dart';
> 
> @JsonSerializable()
> class Sample {
>   final MyExample value;
> 
>   Sample(this.value);
> 
>   factory Sample.fromJson(Map<String, dynamic> json) => _$SampleFromJson(json);
> 
>   Map<String, dynamic> toJson() => _$SampleToJson(this);
> }
> 
> enum MyExample {
>   example0('example0', BackButton());
> 
>   const MyExample(this.value1, this.value2);
> 
>   final String value1;
>   final Widget value2;
> 
>   @override
>   String toString() => '$name: [$value1][$value2]';
> }
> ```
> 
> Works fine for me!
> 
> Have you ran `flutter pub get` recently? Try that.

Can you try with 3 or 4 enums? I think that's prolly the issue

**Comment by kevmoo** [comment]
```dart
import 'package:flutter/material.dart';
import 'package:json_annotation/json_annotation.dart';

part 'sample.g.dart';

@JsonSerializable()
class Sample {
  final MyExample value;

  Sample(this.value);

  factory Sample.fromJson(Map<String, dynamic> json) => _$SampleFromJson(json);

  Map<String, dynamic> toJson() => _$SampleToJson(this);
}

enum MyExample {
  example0('example0', BackButton()),
  example1('example1', CloseButton()),
  example2('example2', BackButton()),
  example3('example3', BackButton());

  const MyExample(this.value1, this.value2);

  final String value1;
  final Widget value2;

  @override
  String toString() => '$name: [$value1][$value2]';
}
```

**Comment by kevmoo** [comment]
This works fine, too!

**Comment by cgutierr-zgz** [comment]
Hi @kevmoo I got it working

I just deleted the local version of flutter and downloaded it again from scratch😅

May all problems be like this one, hahahaha

I don't know what might have been the root issue but I can tell u Flutter version was 3.0.0 and sdk in the project was the one I took the screenshot of

**Comment by iLoveDocs** [comment]
This issue should reopened. I'm also facing it. Here's the question on [StackOverflow](https://stackoverflow.com/q/72230708/12483095).

**Comment by cgutierr-zgz** [comment]
@iLoveDocs 
Try running flutter `pub upgrade` or installing it over, worked for me and my colleagues at work

**Comment by iLoveDocs** [comment]
@cgutierr-zgz 

Thanks but I already ran `flutter pub upgrade` and I'm on 
```
Flutter 3.1.0-0.0.pre.683 • channel master 
Dart 2.18.0 (build 2.18.0-109.0.dev)
```

I don't want to reinstall the Flutter SDK at the moment. But even if it works, this must not be the correct solution to this issue, and therefore I consider that this issue should be reopened.

**Comment by kevmoo** [comment]
This is NOT an issue w/ json_serializable – guessing it's either analyzer or pkg:build

@jakemac53 @natebosch @scheglov – thoughts? Caching issues?

Try deleting `.dart_tool`, run `pub get` the build

**Comment by scheglov** [comment]
It might be caused by using Dart SDK `2.18.0`, instead of `2.17.0`. The reason is that there was a bug in the analyzer, fixed in https://dart-review.googlesource.com/c/sdk/+/243930 and generalized in https://dart-review.googlesource.com/c/sdk/+/244041.

**Comment by daiki1003** [comment]
I got the same error too.
Adding below to `pubspec.yaml` works well for me :)

```yaml
analyzer: ^3.4.1
```

**Comment by kevmoo** [comment]
> I got the same error too. Adding below to `pubspec.yaml` works well for me :)
> 
> ```yaml
> analyzer: ^3.4.1
> ```

NOT a good answer. You want to get the latest `pkg:analyzer`. I'd go w/ deleting `.dart_tool` and trying again!

**Comment by jakemac53** [comment]
You should be able to do a `[dart|flutter] pub upgrade` ideally to fix this? You will definitely need to be on the latest analyzer in order to be able to parse the new syntax.

**Comment by quantosapplications** [comment]
This happening to me too with freezed json_serializable

```

enum UserRole {
  admin('Admin'), supervisor('Supervisor'), simple('Simple');
  final String role;
  const UserRole(this.role);
}

@freezed
class User extends CrudEntity with _$User {
  
  const factory User({ 
    required int id,
    ....
    @JsonKey(fromJson: toLower, toJson: toUpper) required UserRole role,

  }) = _User;

  factory User.fromJson(Map<String, dynamic> json) => _$UserFromJson(json);

  static String? toLower(String? val) => val?.toLowerCase();
  static String? toUpper(String? val) => val?.toUpperCase();

}
```

The output of console

```
[SEVERE] json_serializable:json_serializable on lib/core/classes/user.dart:

This builder requires Dart inputs without syntax errors.
However, package:.../user.dart (or an existing part) contains the following errors.
user.dart:16:28: This requires the 'enhanced-enums' language feature to be enabled.

Try fixing the errors and re-running the build.
```

flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-arm, locale
    it-IT)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.4)
[✓] VS Code (version 1.67.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
fabriziotognetto@MacBook-Pro-di-fabrizio-2 ~ % dart --version
Dart SDK version: 2.17.0 (stable) (Mon May 9 10:36:47 2022 +0200) on "macos_arm64"
```

**Comment by giiyms** [comment]
> This happening to me too with freezed json_serializable, tried all the solutions above..
> 
> ```
> 
> enum UserRole {
>   admin('Admin'), supervisor('Supervisor'), simple('Simple');
>   final String role;
>   const UserRole(this.role);
> }
> 
> @freezed
> class User extends CrudEntity with _$User {
>   
>   const factory User({ 
>     required int id,
>     ....
>     @JsonKey(fromJson: toLower, toJson: toUpper) required UserRole role,
> 
>   }) = _User;
> 
>   factory User.fromJson(Map<String, dynamic> json) => _$UserFromJson(json);
> 
>   static String? toLower(String? val) => val?.toLowerCase();
>   static String? toUpper(String? val) => val?.toUpperCase();
> 
> }
> ```
> 
> The output of console
> 
> ```
> [SEVERE] json_serializable:json_serializable on lib/core/classes/user.dart:
> 
> This builder requires Dart inputs without syntax errors.
> However, package:.../user.dart (or an existing part) contains the following errors.
> user.dart:16:28: This requires the 'enhanced-enums' language feature to be enabled.
> 
> Try fixing the errors and re-running the build.
> ```
> 
> flutter doctor
> 
> ```
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-arm, locale
>     it-IT)
> [✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
> [✓] Xcode - develop for iOS and macOS (Xcode 13.1)
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 2020.3)
> [✓] IntelliJ IDEA Ultimate Edition (version 2020.1.4)
> [✓] VS Code (version 1.67.1)
> [✓] Connected device (2 available)
> [✓] HTTP Host Availability
> 
> • No issues found!
> fabriziotognetto@MacBook-Pro-di-fabrizio-2 ~ % dart --version
> Dart SDK version: 2.17.0 (stable) (Mon May 9 10:36:47 2022 +0200) on "macos_arm64"
> ```

I am using freezed too. Deleting .dart_tool fixed it for me.

**Comment by kevmoo** [comment]
I think we have a work-around here. Looks like there might be an issue with analyzer, but the work around...works. 😄

**Comment by iLoveDocs** [comment]
@kevmoo If deleting the `.dart_tool` directory in the Flutter project (app's directory) is the workaround you are talking about, then I'm sorry it didn't work (or at least for me), and therefore this issue should be reopened. Thanks

**Comment by kevmoo** [comment]
@iLoveDocs – can you provide the output of `flutter doctor` and your `pubspec.lock` file?

**Comment by iLoveDocs** [comment]
@kevmoo  Here it is:

## Flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.1.0-0.0.pre.683, on macOS 12.0.1 21A559 darwin-arm, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Community Edition (version 2021.3.2)
[✓] VS Code (version 1.67.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

## `pubspec.lock`

```
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  _fe_analyzer_shared:
    dependency: transitive
    description:
      name: _fe_analyzer_shared
      url: "https://pub.dartlang.org"
    source: hosted
    version: "34.0.0"
  analyzer:
    dependency: transitive
    description:
      name: analyzer
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.2.0"
  args:
    dependency: transitive
    description:
      name: args
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.3.0"
  async:
    dependency: transitive
    description:
      name: async
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.9.0"
  boolean_selector:
    dependency: transitive
    description:
      name: boolean_selector
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  build:
    dependency: transitive
    description:
      name: build
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.1"
  build_config:
    dependency: transitive
    description:
      name: build_config
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.0"
  build_daemon:
    dependency: transitive
    description:
      name: build_daemon
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.1.0"
  build_resolvers:
    dependency: transitive
    description:
      name: build_resolvers
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.6"
  build_runner:
    dependency: "direct dev"
    description:
      name: build_runner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.11"
  build_runner_core:
    dependency: transitive
    description:
      name: build_runner_core
      url: "https://pub.dartlang.org"
    source: hosted
    version: "7.2.3"
  built_collection:
    dependency: transitive
    description:
      name: built_collection
      url: "https://pub.dartlang.org"
    source: hosted
    version: "5.1.1"
  built_value:
    dependency: transitive
    description:
      name: built_value
      url: "https://pub.dartlang.org"
    source: hosted
    version: "8.1.4"
  characters:
    dependency: transitive
    description:
      name: characters
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.1"
  charcode:
    dependency: transitive
    description:
      name: charcode
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.1"
  checked_yaml:
    dependency: transitive
    description:
      name: checked_yaml
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.1"
  cli_util:
    dependency: transitive
    description:
      name: cli_util
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.5"
  clock:
    dependency: transitive
    description:
      name: clock
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  code_builder:
    dependency: transitive
    description:
      name: code_builder
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.1.0"
  collection:
    dependency: transitive
    description:
      name: collection
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.16.0"
  convert:
    dependency: transitive
    description:
      name: convert
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.1"
  crypto:
    dependency: transitive
    description:
      name: crypto
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.1"
  dart_style:
    dependency: transitive
    description:
      name: dart_style
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.1"
  fake_async:
    dependency: transitive
    description:
      name: fake_async
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.0"
  file:
    dependency: transitive
    description:
      name: file
      url: "https://pub.dartlang.org"
    source: hosted
    version: "6.1.2"
  fixnum:
    dependency: transitive
    description:
      name: fixnum
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.0"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_lints:
    dependency: "direct dev"
    description:
      name: flutter_lints
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.4"
  flutter_localizations:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_test:
    dependency: "direct dev"
    description: flutter
    source: sdk
    version: "0.0.0"
  frontend_server_client:
    dependency: transitive
    description:
      name: frontend_server_client
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.2"
  glob:
    dependency: transitive
    description:
      name: glob
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.2"
  graphs:
    dependency: transitive
    description:
      name: graphs
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  http_multi_server:
    dependency: transitive
    description:
      name: http_multi_server
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.1"
  http_parser:
    dependency: transitive
    description:
      name: http_parser
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.0.0"
  intl:
    dependency: transitive
    description:
      name: intl
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.17.0"
  io:
    dependency: transitive
    description:
      name: io
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.3"
  js:
    dependency: transitive
    description:
      name: js
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.6.4"
  json_annotation:
    dependency: "direct main"
    description:
      name: json_annotation
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.5.0"
  json_serializable:
    dependency: "direct dev"
    description:
      name: json_serializable
      url: "https://pub.dartlang.org"
    source: hosted
    version: "6.2.0"
  lints:
    dependency: transitive
    description:
      name: lints
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.1"
  logging:
    dependency: transitive
    description:
      name: logging
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.2"
  matcher:
    dependency: transitive
    description:
      name: matcher
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.12.11"
  material_color_utilities:
    dependency: transitive
    description:
      name: material_color_utilities
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.4"
  meta:
    dependency: transitive
    description:
      name: meta
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.7.0"
  mime:
    dependency: transitive
    description:
      name: mime
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.1"
  package_config:
    dependency: transitive
    description:
      name: package_config
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.2"
  path:
    dependency: transitive
    description:
      name: path
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.8.1"
  pedantic:
    dependency: "direct dev"
    description:
      name: pedantic
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.11.1"
  pool:
    dependency: transitive
    description:
      name: pool
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.5.0"
  pub_semver:
    dependency: transitive
    description:
      name: pub_semver
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  pubspec_parse:
    dependency: transitive
    description:
      name: pubspec_parse
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.0"
  shelf:
    dependency: transitive
    description:
      name: shelf
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.0"
  shelf_web_socket:
    dependency: transitive
    description:
      name: shelf_web_socket
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.1"
  sky_engine:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.99"
  source_gen:
    dependency: transitive
    description:
      name: source_gen
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.1"
  source_helper:
    dependency: transitive
    description:
      name: source_helper
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.1"
  source_span:
    dependency: transitive
    description:
      name: source_span
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.9.0"
  stack_trace:
    dependency: transitive
    description:
      name: stack_trace
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.10.0"
  stream_channel:
    dependency: transitive
    description:
      name: stream_channel
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  stream_transform:
    dependency: transitive
    description:
      name: stream_transform
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
  string_scanner:
    dependency: transitive
    description:
      name: string_scanner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  term_glyph:
    dependency: transitive
    description:
      name: term_glyph
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.0"
  test_api:
    dependency: transitive
    description:
      name: test_api
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.9"
  timing:
    dependency: transitive
    description:
      name: timing
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.0"
  typed_data:
    dependency: transitive
    description:
      name: typed_data
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.0"
  vector_math:
    dependency: transitive
    description:
      name: vector_math
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.2"
  watcher:
    dependency: transitive
    description:
      name: watcher
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.1"
  web_socket_channel:
    dependency: transitive
    description:
      name: web_socket_channel
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  yaml:
    dependency: transitive
    description:
      name: yaml
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.1.0"
sdks:
  dart: ">=2.17.0 <3.0.0"
```
