### ISSUE TITLE
Generating files in different directories

### ISSUE THREAD

**Issue by Aqluse** [google/json_serializable.dart#1158]
`Dart SDK version: 2.17.1 (stable) (Tue May 17 17:58:21 2022 +0000) on "windows_x64"`

As per [source_gen](https://pub.dev/packages/source_gen#generating-files-in-different-directories) documentation states that generated files output directory could be set in this manner
```
some_cool_builder:
        options:
          build_extensions:
            '^lib/models/{{}}.dart': 'lib/models/generated/{{}}.foo.dart'
```

I tried it this way which actually worked with another codegen tool [(freezed)](https://pub.dev/packages/freezed)
```
targets:
  $default:
    builders:
      json_serializable:
        options:
          build_extensions:
            '{{dir}}/{{name}}.dart': '{{dir}}/gen/{{name}}.g.dart'
```

The package gives me execution output as enclosed below considering which I can assume that the tool tries to check against nailed down set of options. The behaviour observed contradicts with source_gen guide.

```
[INFO] Entrypoint:Generating build script...
[INFO] Entrypoint:Generating build script completed, took 343ms

[SEVERE] json_serializable:json_serializable:

Bad state: Could not parse the options provided for `json_serializable`.
Unrecognized keys: [build_extensions]; supported keys: [any_map, checked, constructor, create_factory, create_to_json, disallow_unrecognized_keys, explicit_to_json, field_rename, generic_argument_factories, ignore_unannotated, include_if_null]
package:json_serializable/builder.dart 42:5   jsonSerializable
package:build_runner                          BuildCommand._run
package:args/command_runner.dart 209:13       CommandRunner.runCommand
package:build_runner                          run
.dart_tool\build\entrypoint\build.dart 28:16  main

```
