### ISSUE TITLE
Custom types are not deserialized in subclasses

### ISSUE THREAD

**Issue by franzlst** [google/json_serializable.dart#1207]
```
dart --version
Dart SDK version: 2.18.0 (stable) (Fri Aug 26 10:22:54 2022 +0000) on "windows_x64"
```

```
pubspec.lock:

[...]
  json_annotation:
    dependency: "direct main"
    description:
      name: json_annotation
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.7.0"
  json_serializable:
    dependency: "direct dev"
    description:
      name: json_serializable
      url: "https://pub.dartlang.org"
    source: hosted
    version: "6.4.0"
[...]
```

Please have a look at the following minimal example:

```dart
import 'package:json_annotation/json_annotation.dart';

part 'json_serialize.g.dart';

@JsonSerializable()
class Child {
  String name;
  Child(this.name);

  factory Child.fromJson(Map<String, dynamic> json) => _$ChildFromJson(json);
  Map<String, dynamic> toJson() => _$ChildToJson(this);
}

@JsonSerializable(explicitToJson: true)
class Parent {
  List<Child> children;
  Parent(this.children);

  factory Parent.fromJson(Map<String, dynamic> json) => _$ParentFromJson(json);
  Map<String, dynamic> toJson() => _$ParentToJson(this);
}

@JsonSerializable(explicitToJson: true)
class Mother extends Parent {
  Mother(children) : super(children);

  factory Mother.fromJson(Map<String, dynamic> json) => _$MotherFromJson(json);
  Map<String, dynamic> toJson() => _$MotherToJson(this);
}
```

This generates the following code:

```dart
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'json_serialize.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Child _$ChildFromJson(Map<String, dynamic> json) => Child(
      json['name'] as String,
    );

Map<String, dynamic> _$ChildToJson(Child instance) => <String, dynamic>{
      'name': instance.name,
    };

Parent _$ParentFromJson(Map<String, dynamic> json) => Parent(
      (json['children'] as List<dynamic>)
          .map((e) => Child.fromJson(e as Map<String, dynamic>))
          .toList(),
    );

Map<String, dynamic> _$ParentToJson(Parent instance) => <String, dynamic>{
      'children': instance.children.map((e) => e.toJson()).toList(),
    };

Mother _$MotherFromJson(Map<String, dynamic> json) => Mother(
      json['children'],
    );

Map<String, dynamic> _$MotherToJson(Mother instance) => <String, dynamic>{
      'children': instance.children.map((e) => e.toJson()).toList(),
    };

```

As you can see, the function `_$ParentFromJson` properly handles the custom class `Child` and calls `fromJson` on it for its deserialization.

However, in the function for the subclass -- `_$MotherToJson` -- the member `children` is not deserialized.

On the serialization side, for both the class `Parent` (`_$ParentToJson`) and the subclass `Mother` (`_$MotherToJson`), the member children gets properly serialized (´e.toJson()´).

I already tried the suggestion found in https://github.com/google/json_serializable.dart/issues/918 to add a `JsonConverter` for `Child`, but this only affected the serialization side and did not change the missing deserialization of the `children` property in the subclass `Mother`.

Am I doing something wrong or is this a bug?
