### ISSUE TITLE
Add `ignore_for_file: non_constants_identifier_names` to `g.dart` file

### ISSUE THREAD

**Issue by bambinoua** [google/json_serializable.dart#1287]
It would be good to add `// ignore_for_file: non_constants_identifier_names` to generate `g.dart` file to avoid this warning message
```
The variable name `_$$_UserSettingsFromJson` isn't a lowerCamelCase identifier.
Try to change the name to follow the lowerCamelCase style.
```

**Comment by kevmoo** [comment]
See https://github.com/dart-lang/source_gen/tree/master/source_gen#ignore_for_file

**Comment by bambinoua** [comment]
@kevmoo I tried to do what you advised in previous post, so I created a `build.yaml` with content
```yaml
targets:
  $default:
    builders:
      source_gen:combining_builder:
        options:
          ignore_for_file:
          - non_constant_identifier_names
```
Is still get lint the same warnings. What I did wrong?
