### ISSUE TITLE
Target generate_for conflicts - outputs must be unique across builders

### ISSUE THREAD

**Issue by idraper** [google/json_serializable.dart#683]
dart --version
```
Dart VM version: 2.8.2 (stable) (Mon May 11 15:06:42 2020 +0200) on "windows_x64"
```

I am creating a generator package for my dart package, which also uses json_serializable (v3.2.0). When running my builder, I get the following error:
```
Conflicting outputs
Both my_builder:annotationBuilder and source_gen:combining_builder may output lib/base/converter.g.dart. Potential outputs must be unique across all builders. See https://github.com/dart-lang/build/blob/master/docs/faq.md#why-do-builders-need-unique-outputs
```

I understand why their outputs must be unique, but I have configured the `generate_for` option so their files do not conflict. Here is my `build.yaml`:
```
targets:
  $default:
    builders:
      json_serializable:
        enabled: true
        generate_for:
          - lib/annotations/**
      my_builder|annotationBuilder:
        enabled: true
        generate_for:
          - lib/base/converter.dart
```

I am wondering if it is possible to exclude folders/files from json_serializable so I can run both builders without conflict.

I created a test project with two test generators with the exact same file structure for my target project (and same build, but no json_serializable) and it ran without issue.
