### ISSUE TITLE
Documentation for using the new @JsonSerializable(genericArgumentFactories: true) (3.5.0)

### ISSUE THREAD

**Issue by PhilipSA** [google/json_serializable.dart#723]
I am trying  to take advantage of the new `genericArgumentFactories` in 3.5.0 version but can't figure out how to call the `fromJson` function.

Here is what i tried:
`
ApiResponse.fromJson(json.decode(apiData.body), NameDto.fromJson)`

But this gives me the error: 
`The getter 'fromJson' isn't defined for the type 'NameDto'.`

Is there an example/documentation on how to call these new function? If not could one be added please. I have searched but did not find any.

Classes and dependencies i use:

```
import 'package:json_annotation/json_annotation.dart';

part 'ApiResponse.g.dart';

@JsonSerializable(genericArgumentFactories: true)
class ApiResponse<T> {
  ApiResponse(this.successful, this.errorCode, this.errorMessage, this.data);

  @JsonKey(name: 'Successful')
  final bool successful;
  @JsonKey(name: 'ErrorCode')
  final String errorCode;
  @JsonKey(name: 'ErrorMessage')
  final String errorMessage;
  @JsonKey(name: 'Data')
  final T data;

  factory ApiResponse.fromJson(Map<String, dynamic> json, T Function(Object json) fromJsonT) => _$ApiResponseFromJson(json, fromJsonT);
  Map<String, dynamic> toJson(Object Function(T value) toJsonT) => _$ApiResponseToJson(this, toJsonT);
}
```

```
@JsonSerializable()
class NameDto {
  NameDto (this.firstName, this.lastName);

  final String firstName;
  final String lastName;

  factory NameDto.fromJson(Map<String, dynamic> json) => _$NameDtoFromJson(json);
  Map<String, dynamic> toJson() => _$NameDto ToJson(this);
}
```

```
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  json_annotation: ^3.0.0
  http: ^0.12.2
  analyzer: 0.39.14
  flutter_simple_dependency_injection: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^3.5.0
  build_runner: ^1.0.0
```
