### ISSUE TITLE
Null safety version on pub dev

### ISSUE THREAD

**Issue by nank1ro** [google/json_serializable.dart#821]
Hello,

I can't find a null safety version of json_serializable on pub dev.
Can you publish one please?
I've seen this release `json_serializable-v4.0.0-nullsafety.0` here on github.
I've tried to use it with:
```
json_serializable:
    git:
      url: git://github.com/google/json_serializable.dart.git
      ref: 'json_serializable-v4.0.0-nullsafety.0'
      path: 'json_serializable/'
```
but when I run `dart pub outdated --mode=null-safety`
I get back:
`json_serializable  ✗4.0.0-nullsafety.0 (git)  ✗4.0.0-nullsafety.0 (git)  ✗4.0.0-nullsafety.0 (git)  ✗4.0.0-nullsafety.0 (git) `
so this release doesn't support null-safety yet

**Comment by nank1ro** [comment]
Right know I was able to use the null safety version using:
```
json_serializable:
    git:
      url: git://github.com/google/json_serializable.dart.git
      ref: 'json_serializable-v4.0.0-nullsafety.0'
      path: 'json_serializable/'
```
