### ISSUE TITLE
FromJson method in .g.dart file does not consider nullable input parameter

### ISSUE THREAD

**Issue by scatboy777** [google/json_serializable.dart#896]
I have an issue with the code generated in the .g.dart file

In my model class I have an attribute with a custom Json formatter:

```
@JsonKey(fromJson: _fromJsonGeoPoint, toJson: _toJsonGeoPoint)
  GeoPoint? geopoint;
```
And the fromJson / toJson are as follow:

```
static GeoPoint? _fromJsonGeoPoint(Map<String, dynamic>? json) {
    if (json != null) {
      return GeoPoint(json['latitude'], json['longitude']);
    } else {
      return null;
    }
  }

  static Map<String, dynamic>? _toJsonGeoPoint(GeoPoint? geoPoint) {
    if (geoPoint == null) {
      return null;
    }
    return {"latitude": geoPoint.latitude, "longitude": geoPoint.longitude};
  }
```
BUT in the .g.dart file the input parameter is missing the "?":
`geopoint: Event._fromJsonGeoPoint(json['geopoint'] as Map<String, dynamic>),`

This is blocking me because this field is nullable...my only solution so far is to update the .g.dart file manually.

Any help will be much appreciated !

This is an extract of my pub spec.yaml file:

 ```
 json_annotation: ^4.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^4.1.2
  build_runner: ^2.0.3  
```

Thank you in advance for your help.

For information I have originally reported the issue [here](https://github.com/dart-lang/build/issues/3106) but was asked to transfer it in this project.
