### ISSUE TITLE
Version solving fails on flutter channels below dev

### ISSUE THREAD

**Issue by Rexios80** [google/json_serializable.dart#944]
```
Because json_serializable >=5.0.0 depends on analyzer ^2.0.0 which depends on meta ^1.7.0, json_serializable >=5.0.0 requires meta ^1.7.0.
And because every version of flutter_test from sdk depends on meta 1.4.0, json_serializable >=5.0.0 is incompatible with flutter_test from sdk.
So, because vrc_chat depends on both flutter_test any from sdk and json_serializable ^5.0.0, version solving failed.
Running "flutter pub get" in vrc_chat...                                
pub get failed (1; So, because vrc_chat depends on both flutter_test any from sdk and json_serializable ^5.0.0, version solving failed.)
```

On a fresh flutter channel beta. Resolving fails on stable too. I had to go all the way to the dev channel for it to work.

**Comment by kevmoo** [comment]
This is the nature of Flutter pinning dependencies. You'll have to wait for the current dev branch to make it to beta --> stable.

**Comment by kevmoo** [comment]
...in the meantime, use `^4.0.0`

**Comment by rmahmadkhan** [comment]
for me using `any` for all 3 packages instead of version number solved the issue.

**Comment by nyck33** [comment]
`^4.0.0` still resolves to `4.1.0`?  For me the error does not go away.

```
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.0-dev.7
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^1.0.0-dev.7
  uuid:
  http: 
  json_annotation: ^4.0.0
  freezed: ^0.14.5 
  freezed_annotation: ^0.14.3 
  json_serializable: ^5.0.0
```
