### ISSUE TITLE
Error json_annotation >=4.1.0 depends on meta ^1.4.0

### ISSUE THREAD

**Issue by destemidosistemas** [google/json_serializable.dart#959]
Hi. I've an error when I install json_serializable in a new project.

Error: "Because json_annotation >=4.1.0 depends on meta ^1.4.0 and every version of flutter from sdk depends on meta 1.3.0, json_annotation >=4.1.0 is incompatible with flutter from sdk."

I haven't started application development yet. I'm just trying to install the package.

Below, output of command "flutter --version":

Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git  
Framework • revision f4abaa0735 (5 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4

Below, my pubspec.yaml:

```
name: gnall
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.1.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^5.0.0

flutter:
  uses-material-design: true
```
